Crud
GunplaOnlineShop/GunplaOnlineShop pull request #5
Opened 2020-08-03 20:44 UTC by TiannanXu

2020-08-03 21:32 UTC, ExploreNcrack commented on GunplaOnlineShop/GunplaOnlineShop/Controllers/ItemRepositoryController.cs
> +        public async Task<IActionResult> ItemRepositoryCollection([Bind("PageNumber,SelectedOrder")] CollectionViewModel model)
should call it just Index

2020-08-03 22:03 UTC, ExploreNcrack requested changes

2020-08-03 22:03 UTC, ExploreNcrack commented on GunplaOnlineShop/GunplaOnlineShop/Controllers/ItemRepositoryController.cs
> +        public IActionResult ItemCreate(ItemViewModel model)
Just call it Create()

2020-08-03 22:03 UTC, ExploreNcrack commented on GunplaOnlineShop/GunplaOnlineShop/Controllers/ItemRepositoryController.cs
> +{
Need to decorate with `[Authorize]` not everyone can access these methods, only the logged in user with admin role can

2020-08-03 22:03 UTC, ExploreNcrack commented on GunplaOnlineShop/GunplaOnlineShop/Controllers/ItemRepositoryController.cs
> +        public IActionResult ItemCreate(ItemViewModel model)
this action only need to return a static page, no user input is needed, thus no model/user-data should take in

2020-08-03 22:03 UTC, ExploreNcrack commented on GunplaOnlineShop/GunplaOnlineShop/Controllers/ItemRepositoryController.cs
> +                if (_context.Items.Any(c => c.Name == model.Name)) return View("ItemCreate", model);
if item with this name exists why return the same create view???

2020-08-03 22:03 UTC, ExploreNcrack commented on GunplaOnlineShop/GunplaOnlineShop/Controllers/ItemRepositoryController.cs
> +                    if (model.GalleryPhotos != null && model.GalleryPhotos.Count > 0)
Gallery photo upload is not working properly

2020-08-03 22:03 UTC, ExploreNcrack commented on GunplaOnlineShop/GunplaOnlineShop/Views/ItemRepository/ItemCreate.cshtml
> +﻿@model GunplaOnlineShop.ViewModels.ItemViewModel
need to have a back link

2020-08-03 22:03 UTC, ExploreNcrack commented on GunplaOnlineShop/GunplaOnlineShop/Views/ItemRepository/ItemEdit.cshtml
> +﻿@model GunplaOnlineShop.ViewModels.ItemViewModel
need to have a back link

2020-08-03 22:03 UTC, ExploreNcrack commented on GunplaOnlineShop/GunplaOnlineShop/Views/ItemRepository/ItemEdit.cshtml
> +                <button type="submit" class="btn btn-primary btn-lg">Edit</button>
Should call it `Save`

2020-08-06 15:26 UTC, ExploreNcrack commented on GunplaOnlineShop/GunplaOnlineShop/Controllers/ItemRepositoryController.cs
> +        public IActionResult Create(ItemViewModel model)
`[ValidateAntiForgeryToken]`

2020-08-06 15:28 UTC, ExploreNcrack requested changes

2020-08-06 15:28 UTC, ExploreNcrack commented on GunplaOnlineShop/GunplaOnlineShop/Controllers/ItemRepositoryController.cs
> +        public IActionResult Delete(int? id)
[ValidateAntiForgeryToken]

2020-08-06 15:28 UTC, ExploreNcrack commented on GunplaOnlineShop/GunplaOnlineShop/Controllers/ItemRepositoryController.cs
> +        public IActionResult ItemEdit(int id)
[ValidateAntiForgeryToken]

2020-08-08 21:46 UTC, TiannanXu commented on GunplaOnlineShop/GunplaOnlineShop/Controllers/ItemRepositoryController.cs
> +                    if (model.GalleryPhotos != null && model.GalleryPhotos.Count > 0)
Not sure the problem, it works just fine on my PC

2020-08-12 21:51 UTC, merged